language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - 2.7
matrix:
  fast_finish: true
env:
  matrix:
    - PLONE_VERSION=5.0
    - PLONE_VERSION=5.1
install:
  - pip install -r requirements.txt
  - sed -ie "s#test-5.0#test-$PLONE_VERSION#" buildout.cfg
  - bin/buildout -N buildout:download-cache=downloads -c tests.cfg annotate
  - bin/buildout -N buildout:download-cache=downloads -c tests.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/code-analysis
  - bin/coverage run bin/test
after_success:
  - bin/coveralls
